BiocManager::install("DAPAR") # Tools for the Differential Analysis of Proteins Abundance with R
BiocManager::install("rrvgo") # Reduce and visualize lists of Gene Ontology terms by identifying redudance based on semantic similarity.
                              # Very Good....  methods for plotting and interpreting the results
BiocManager::install("ropls") # Very good.... PCA, PLS(-DA) and OPLS(-DA) for multivariate analysis and feature selection of omics data
BiocManager::install('PCAtools') # Very good......   PCAtools: everything Principal Component Analysis
install.packages("pcaMethods")
BiocManager::install("POMA")     # Tools for Omics Data Analysis
BiocManager::install("OMICsPCA") # An R package for quantitative integration and analysis of multiple omics assays from heterogeneous samples
BiocManager::install("simplifyEnrichment")  # A Shiny app to interactively visualize clustering results
BiocManager::install("enrichplot")         #Visualization of Functional Enrichment Result
BiocManager::install("enrichViewNet")    #Very good...  From functional enrichment results to biological networks
BiocManager::install("fenr")          #Fast functional enrichment for interactive applications
BiocManager::install("clusterProfiler", force = TRUE) 
BiocManager::install("org.Hs.eg.db")
BiocManager::install("org.Mm.eg.db")
BiocManager::install("org.Rn.eg.db")
BiocManager::install("org.EcK12.eg.db")
BiocManager::install("PerseusR")
install.packages('pheatmap')
install.packages("DOSE")
BiocManager::install("enrichplot")
install.packages("ggupset")
BiocManager::install("GOplot")
#install.packages(c("devtools", "tidyverse", "tinytex", "BiocManager"))
BiocManager::install(c('ProtGenerics', 'MSnbase', 'limma'), update=T, ask=F)
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never")
BiocManager::install("BioNet")
BiocManager::install("STRINGdb")
BiocManager::install("MeSHDbi")
BiocManager::install("meshes")
BiocManager::install("RDAVIDWebService")
BiocManager::install("ReactomePA")
BiocManager::install("pathview")
install.packages("wordcloud")
BiocManager::install("DLBCL")
install.packages("remotes")
remotes::install_github('davetang/romim') # OMIM database
BiocManager::install("ComplexHeatmap")
BiocManager::install("ComplexUpset")
BiocManager::install("ggrepel")
BiocManager::install("ggfortify")
BiocManager::install("ggcorrplot")
BiocManager::install(c('ProtGenerics', 'MSnbase', 'limma'), update=T, ask=F)
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("ftwkoopmans/msdap", upgrade = "never") # don't update dependencies if not needed

library(ggplot2)
library(tidyr)
library(tibble)
library(rlang)
library(dplyr)
library(ProtGenerics)
library(msdap)
library(diann)
library(org.Hs.eg.db)
library(clusterProfiler) 
library(GOplot)
library(DOSE) 
library(enrichplot)
library(PerseusR)
library(msdap)
library(goat)
library(AnnotationDbi)
library(GO.db)
library(msigdbr)
library(BioNet)
library(DLBCL)
library(pathview)
library(wordcloud)
library(BiocManager)
library(ReactomePA)
library(MeSHDbi)
library(MeSH.Hsa.eg.db)
library(STRINGdb)
library(XML)
library(magrittr)
library(xml2)
library(romim)


library(readxl)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(dplyr)
library(stringr)
library(eulerr)
library(readxl) 
library(VennDiagram)
library(ggVennDiagram)
library(ggvenn)
library(ggplot2) 
library(ComplexUpset)
library(ggrepel)
library(ggfortify)

library(org.Hs.eg.db)
library(clusterProfiler) 
library(GOplot)
library(DOSE) 
library(enrichplot)
library(PerseusR)
library(msdap)
library(goat)
library(AnnotationDbi)
library(GO.db)
library(msigdbr)
#BiocManager::install("pathview")
library(pathview)
library(ReactomePA)

library(readxl)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(dplyr)
library(stringr)
library(eulerr)
library(readxl) 
library(VennDiagram)
library(ggVennDiagram)
library(ggvenn)
library(ggplot2) 
library(ComplexUpset)
library(ggrepel)
library(ggfortify)

library(BiocManager)
library(BioNet)
library(ComplexHeatmap)
library(cowplot)
library(DEqMS)
library(devtools)
library(DIAgui)
library(DLBCL)
library(ellipse)
library(enrichplot)
library(eulerr)
library(genoPlotR)
library(ggcorrplot)
library(ggplot2)
library(ggpointdensity)
library(ggupset)
library(ggvenn)
library(goat)
library(GOplot)
library(iq)
library(janitor)
library(KEGGgraph)
library(limma)
library(MeSHDbi)
library(msEmpiRe)
library(msigdbr)
library(mzR)
library(mzID)
library(org.Dm.eg.db)
library(org.EcK12.eg.db)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(org.Rn.eg.db)
library(org.Sc.sgd.db)
library(palmerpenguins)
library(Path2PPI)
library(pathview)
library(PCAtools)
library(pcaMethods)
library(Peptides)
library(PerseusR)
library(pheatmap)
library(proteoDA)
library(ProtGenerics)
library(RCy3)
library(reactome.db)
library(ReactomePA)
library(shiny)
library(STRINGdb)
library(tidyproteomics)
library(treemap)
library(UpSetR)
library(viridis)
library(wordcloud)

